server:
  port: 8081

eureka:
  client:
    registry-fetch-interval-seconds: 5
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: todo-service
  data:
    mongodb:
      database: boot_reactive_todo
      port: 27017
      host: localhost

  rabbitmq:
    host: localhost
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        todo-events-output-channel:
          # this will be my exchange
          destination: todo-events-output
      default:
        content-type: application/json # review this


  boot:
    admin:
      client:
        # at this moment in time admin-server does not have credentials, so user and password are not important
        username: admin
        password: admin
        url: http://localhost:8083

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'


logging:
  level:
    root: warn