eureka:
  client:
    registry-fetch-interval-seconds: 5
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: proxy-service
  boot:
    admin:
      client:
        # at this moment in time admin-server does not have credentials, so user and password are not important
        username: admin
        password: admin
        url: http://localhost:8083
server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: '*'
